import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — TokenSavr" },
      {
        name: "description",
        content:
          "The terms governing your use of TokenSavr, an AI strategy planner for credit-based AI coding platforms.",
      },
      { property: "og:title", content: "Terms of Service — TokenSavr" },
      {
        property: "og:description",
        content: "Read the terms governing your use of TokenSavr.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  const updated = "April 2026";

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12">
      <header className="mb-10">
        <p className="text-xs uppercase tracking-wider text-muted-foreground">Legal</p>
        <h1 className="mt-2 text-3xl sm:text-4xl font-semibold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-muted-foreground">Last updated: {updated}</p>
      </header>

      <div className="space-y-10 text-sm leading-relaxed text-muted-foreground">
        <Section title="1. Agreement">
          <p>
            By creating an account or using TokenSavr ("the Service"), you agree to these
            Terms of Service. If you do not agree, do not use the Service. These terms form
            a binding agreement between you and the operators of TokenSavr ("we", "us").
          </p>
        </Section>

        <Section title="2. What TokenSavr does">
          <p>
            TokenSavr is a planning tool that uses AI to generate step-by-step strategies
            for building software with credit-based AI coding platforms (e.g. Lovable,
            Cursor, Bolt, v0, Claude, ChatGPT). All credit costs, savings figures, time
            estimates, and platform recommendations are <strong>rough estimates</strong> —
            not guarantees. Actual costs and outcomes depend on the platform's own pricing,
            your prompts, and many other factors outside our control.
          </p>
        </Section>

        <Section title="3. Account & eligibility">
          <p>
            You must be at least 13 years old to use TokenSavr. You are responsible for
            keeping your login credentials confidential and for all activity under your
            account. Notify us immediately if you suspect unauthorized access.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Use the Service to violate any law or third-party right.</li>
            <li>
              Attempt to reverse-engineer, scrape, or overwhelm the Service or its
              underlying AI providers.
            </li>
            <li>
              Submit prompts containing personal data of others, malware, or content that
              infringes intellectual property.
            </li>
            <li>
              Resell, sublicense, or rebrand TokenSavr outputs as if they were a separate
              commercial product.
            </li>
          </ul>
        </Section>

        <Section title="5. AI-generated content">
          <p>
            Strategies, step plans, and cost estimates are generated by third-party AI
            models. They may be inaccurate, incomplete, or out of date. You are solely
            responsible for reviewing every recommendation before acting on it. We disclaim
            liability for decisions made based on AI output.
          </p>
        </Section>

        <Section title="6. Your content">
          <p>
            You retain ownership of the project ideas, prompts, and notes you submit. By
            using TokenSavr you grant us a limited license to process this content in
            order to operate the Service (including sending it to AI providers to generate
            your strategy). We do not sell your content.
          </p>
        </Section>

        <Section title="7. Third-party platforms">
          <p>
            TokenSavr references and links to third-party AI coding platforms. We are not
            affiliated with, endorsed by, or responsible for those platforms. Their
            pricing, terms, and availability may change at any time.
          </p>
        </Section>

        <Section title="8. Service availability">
          <p>
            The Service is provided "as is" without warranty of any kind. We may modify,
            suspend, or discontinue features at any time. We aim for high uptime but do
            not guarantee uninterrupted access.
          </p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            To the fullest extent permitted by law, TokenSavr and its operators are not
            liable for any indirect, incidental, or consequential damages, lost profits,
            or wasted credits arising from use of the Service. Our total liability for any
            claim is limited to the amount you paid us in the 12 months prior, or USD 50
            if you have not paid us anything.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            You may delete your account at any time from Settings. We may suspend or
            terminate accounts that violate these terms. On termination, your saved
            strategies and progress will be deleted within a reasonable period.
          </p>
        </Section>

        <Section title="11. Changes to these terms">
          <p>
            We may update these terms occasionally. Material changes will be communicated
            via the Service or by email. Continued use after a change means you accept the
            updated terms.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            Questions about these terms? Reach out via the support contact listed on our{" "}
            <Link to="/" className="text-primary hover:underline">
              homepage
            </Link>
            .
          </p>
        </Section>
      </div>

      <div className="mt-12 border-t border-border/60 pt-6 text-xs text-muted-foreground">
        See also our{" "}
        <Link to="/privacy" className="text-primary hover:underline">
          Privacy Policy
        </Link>
        .
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-medium text-foreground mb-2">{title}</h2>
      {children}
    </section>
  );
}
