/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingSyncRouteImport } from './routes/pricing-sync'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateStrategyRouteImport } from './routes/api.generate-strategy'
import { Route as ApiPublicSyncModelPricingRouteImport } from './routes/api/public/sync-model-pricing'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingSyncRoute = PricingSyncRouteImport.update({
  id: '/pricing-sync',
  path: '/pricing-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStrategyRoute = ApiGenerateStrategyRouteImport.update({
  id: '/api/generate-strategy',
  path: '/api/generate-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncModelPricingRoute =
  ApiPublicSyncModelPricingRouteImport.update({
    id: '/api/public/sync-model-pricing',
    path: '/api/public/sync-model-pricing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/generate': typeof GenerateRoute
  '/pricing': typeof PricingRoute
  '/pricing-sync': typeof PricingSyncRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tips': typeof TipsRoute
  '/api/generate-strategy': typeof ApiGenerateStrategyRoute
  '/api/public/sync-model-pricing': typeof ApiPublicSyncModelPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/generate': typeof GenerateRoute
  '/pricing': typeof PricingRoute
  '/pricing-sync': typeof PricingSyncRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tips': typeof TipsRoute
  '/api/generate-strategy': typeof ApiGenerateStrategyRoute
  '/api/public/sync-model-pricing': typeof ApiPublicSyncModelPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/generate': typeof GenerateRoute
  '/pricing': typeof PricingRoute
  '/pricing-sync': typeof PricingSyncRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tips': typeof TipsRoute
  '/api/generate-strategy': typeof ApiGenerateStrategyRoute
  '/api/public/sync-model-pricing': typeof ApiPublicSyncModelPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/generate'
    | '/pricing'
    | '/pricing-sync'
    | '/privacy'
    | '/results'
    | '/settings'
    | '/terms'
    | '/tips'
    | '/api/generate-strategy'
    | '/api/public/sync-model-pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/generate'
    | '/pricing'
    | '/pricing-sync'
    | '/privacy'
    | '/results'
    | '/settings'
    | '/terms'
    | '/tips'
    | '/api/generate-strategy'
    | '/api/public/sync-model-pricing'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/generate'
    | '/pricing'
    | '/pricing-sync'
    | '/privacy'
    | '/results'
    | '/settings'
    | '/terms'
    | '/tips'
    | '/api/generate-strategy'
    | '/api/public/sync-model-pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  GenerateRoute: typeof GenerateRoute
  PricingRoute: typeof PricingRoute
  PricingSyncRoute: typeof PricingSyncRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TipsRoute: typeof TipsRoute
  ApiGenerateStrategyRoute: typeof ApiGenerateStrategyRoute
  ApiPublicSyncModelPricingRoute: typeof ApiPublicSyncModelPricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-sync': {
      id: '/pricing-sync'
      path: '/pricing-sync'
      fullPath: '/pricing-sync'
      preLoaderRoute: typeof PricingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-strategy': {
      id: '/api/generate-strategy'
      path: '/api/generate-strategy'
      fullPath: '/api/generate-strategy'
      preLoaderRoute: typeof ApiGenerateStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-model-pricing': {
      id: '/api/public/sync-model-pricing'
      path: '/api/public/sync-model-pricing'
      fullPath: '/api/public/sync-model-pricing'
      preLoaderRoute: typeof ApiPublicSyncModelPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  GenerateRoute: GenerateRoute,
  PricingRoute: PricingRoute,
  PricingSyncRoute: PricingSyncRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TipsRoute: TipsRoute,
  ApiGenerateStrategyRoute: ApiGenerateStrategyRoute,
  ApiPublicSyncModelPricingRoute: ApiPublicSyncModelPricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
